spring:
  config:
    import: optional:file:./.env[.properties] # read environment variables from .env file
  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:pkodb}
    username: ${PGUSER:postgres}
    password: ${PGPASSWORD:mysecretpw}
    dbcp2:
      max-wait-millis: 30000
      validation-query: select 1
      validation-query-timeout: 30
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  logging:
    level:
      org.springframework.security: debug
#  docker:
#    compose:
#      lifecycle-management: start-only

server:
  host: ${HOST:localhost}
  port: ${PORT:8080}

springdoc:
  pathsToMatch: /api/**
