package com.gusrylmubarok.sinaukoding.hris.common;

public interface StatusCode {

    String SAVE_SUCCESS = "0010 : SAVE SUCCESS";
    String SAVE_FAILED = "0011 : SAVE FAILED";
    String UPDATE_SUCCESS = "0012 : UPDATE SUCCESS";
    String UPDATE_FAILED = "0013 : UPDATE FAILED";
    String DELETE_SUCCESS = "0014 : DELETE SUCCESS";
    String DELETE_FAILED = "0015 : DELETE FAILED";

    String OPERATION_SUCCESS = "1112 : OPERATION SUCCESS";
    String OPERATION_FAILED = "1113 : OPERATION FAILED";

    String PASSWORD_OR_USER_NOT_REGISTERED = "0111 : PASSWORD OR USER NOT REGISTERED";
    String LOGIN_SUCCESS = "0112 : LOGIN SUCCESS";
    String LOGIN_FAILED = "0113 : LOGIN FAILES";

}

